sudo: false
language: python
python:
  - "3.5"
env:
  global:
    - RUNTEST_ARGS="-v --noinput"
  matrix:
    # Quality checks
    - TOXENV=flake8
    # Supported python/django versions
    - TOXENV=py35-django-2
install:
  - pip install tox
script: tox
