sudo: false
language: python
python:
  - "3.5"
env:
  global:
    - COVERAGE=1 RUNTEST_ARGS="-v --noinput"
  matrix:
    # Quality checks
    - TOXENV=flake8
    # Supported python/django versions
    - TOXENV=py27-django-18
    - TOXENV=py27-django-19
    - TOXENV=py27-django-110
    - TOXENV=py35-django-18
    - TOXENV=py35-django-19
    - TOXENV=py35-django-110
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgeoip-dev
install:
  - pip install tox coveralls
before_script:
  - coverage erase
script: tox
after_success: coveralls
